obstacle_range: 0.5 
raytrace_range: 1.0 
robot_radius: 0.25 
inflation_radius: 0.25
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}

