wheelchair_model:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    joints:
         - Seatback_JOINT_1
         - Footrest_JOINT_1
         - Stick_JOINT

  # Position Controllers ---------------------------------------
  Seatback_JOINT_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Seatback_JOINT_1
    pid: {p: 150.0, i: 0.01, d: 15.0}


  Footrest_JOINT_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Footrest_JOINT_1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Stick_JOINT_position_controller:
    type: effort_controllers/JointPositionController
    joint: Stick_JOINT
    pid: {p: 100.0, i: 0.01, d: 10.0}


